apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers: 
      - name: site-conversao
        image: ra1z3nbr/conversao-temperatura
        ports:
        - containerPort: 8080


